class ErrorCodes:
    """Códigos de error del sistema"""
    # HU-001
    EMAIL_EXISTS = "EMAIL_EXISTS"
    INVALID_DATA = "INVALID_DATA"
    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    INVALID_PHONE = "INVALID_PHONE"
    UNDERAGE_USER = "UNDERAGE_USER"
    
    # HU-002
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_BLOCKED = "ACCOUNT_BLOCKED"
    USER_INACTIVE = "USER_INACTIVE"
    
    # HU-003
    EMAIL_UPDATE_NOT_ALLOWED = "EMAIL_UPDATE_NOT_ALLOWED"
    INVALID_CURRENT_PASSWORD = "INVALID_CURRENT_PASSWORD"
    
    # HU-004
    ADMIN_REQUIRED = "ADMIN_REQUIRED"
    USER_ALREADY_INACTIVE = "USER_ALREADY_INACTIVE"
    LAST_ADMIN_CANNOT_BE_DEACTIVATED = "LAST_ADMIN_CANNOT_BE_DEACTIVATED"
    USER_HAS_ACTIVE_RESERVATIONS = "USER_HAS_ACTIVE_RESERVATIONS"
    CANNOT_DESACTIVATE_SELF = "CANNOT_DESACTIVATE_SELF"
    
    #HU-009
    VEHICLE_NOT_FOUND = "VEHICLE_NOT_FOUND"
    VEHICLE_NOT_AVAILABLE = "VEHICLE_NOT_AVAILABLE"
    
    #HU-010
    MAX_ACTIVE_RESERVATIONS = "MAX_ACTIVE_RESERVATIONS"
    
    #HU-011
    RESERVATION_NOT_FOUND = "RESERVATION_NOT_FOUND"
    NOT_RESERVATION_OWNER = "NOT_RESERVATION_OWNER"
    INVALID_RESERVATION_STATUS = "INVALID_RESERVATION_STATUS"
    RESERVATION_ALREADY_STARTED = "RESERVATION_ALREADY_STARTED"
    
    #HU-017
    PAYMENT_NOT_CONFIRMED = "PAYMENT_NOT_CONFIRMED"
    
    #HU-018
    QR_EXPIRED = "QR_EXPIRED"
    QR_ALREADY_USED = "QR_ALREADY_USED"
    INVALID_QR_CODE = "INVALID_QR_CODE"
    RESERVATION_NOT_ACTIVE = "RESERVATION_NOT_ACTIVE"
    NOT_RESERVATION_OWNER = "NOT_RESERVATION_OWNER"
    
    #HU-019
    QR_INVALID_OR_EXPIRED = "QR_INVALID_OR_EXPIRED"

class HttpStatus:
    """Códigos HTTP"""
    OK = 200
    CREATED = 201
    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    FORBIDDEN = 403
    NOT_FOUND = 404
    CONFLICT = 409 
    INTERNAL_ERROR = 500
    
